'''
Neuropath streamlit website

Created by: Victoria Rachleff
Created on: 4/30/24 
Updated on: 05/24/24
'''
import os
import io
import streamlit as st
import pandas as pd
import numpy as np
import scanpy as sc
import matplotlib.pyplot as plt
import altair as alt
from streamlit_image_zoom import image_zoom
from PIL import Image
from typing import Union, Optional, Tuple, NewType
from IPython.display import HTML
import sys
sys.path.insert(0, '..')


st.set_page_config(
    page_title="Hello",
    page_icon="👋",
    layout="wide",
)

# read in quant neuropath (from sea-ad website)
filepath = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "data", "MTG_neuropath.csv")
neuropath_df = pd.read_csv(filepath)

source = neuropath_df

st.title('Model Predictions of Quantitative Neuropathology Markers Over Pseudotime')
st.write('Plot 5: Generated by Janna Hong using Plotly. Visualizes the observed data and model predictions for various layers and features related to quant neuropath data of Alzheimers Disease patients, showing the relationship over pseudotime to infer the progression and dynamics of neuropathological markers. On the right, the heatmap serves as a tool for visualizing multi-layered data over time, providing insights into the dynamics of the measured features.')
st.write('Interaction: Select a feature of interest (e.g., AT8) and cortical layer (e.g, Layer 3) from the dropdown menu to see specific model predictions. Option to pan, zoom, and select values of interest.')

import streamlit.components.v1 as components


col1, col_padding, col2 = st.columns([1, 0.05, 1])

with col1: 
    HtmlFile = open("html/white_MTG_INFERENCE.html", 'r', encoding='utf-8')
    source_code = HtmlFile.read() 
    # print(source_code)
    components.html(source_code,  height = 600, width = 850)

with col2: 
    HtmlFile = open("html/Pink_MTG_INFERENCE_HEATMAP.html", 'r', encoding='utf-8')
    source_code = HtmlFile.read() 
    # print(source_code)
    components.html(source_code,  height = 600, width = 850)